# Generated by Django 4.1.1 on 2022-09-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_timer', '0002_rename_task_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'uid', 'verbose_name_plural': 'uid'},
        ),
    ]
