# Generated by Django 4.1.1 on 2022-09-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_timer', '0003_alter_time_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='timer',
            field=models.CharField(blank=True, max_length=20, verbose_name='timer'),
        ),
    ]
