# Generated by Django 4.1.1 on 2022-10-05 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_timer', '0005_alter_time_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='name')),
                ('user_number', models.CharField(max_length=12, verbose_name='number')),
                ('user_time_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_time_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(max_length=20, verbose_name='uid')),
                ('rid', models.CharField(max_length=20, verbose_name='rid')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
    ]
